"""empty message

Revision ID: 9f52e39bb755
Revises: beb927995179
Create Date: 2019-10-13 20:58:08.200405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f52e39bb755'
down_revision = 'beb927995179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_likes_timestamp'), 'likes', ['timestamp'], unique=False)
    op.add_column('post', sa.Column('count_likes', sa.Integer(), nullable=True))
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('post', 'count_likes')
    op.drop_index(op.f('ix_likes_timestamp'), table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
