"""empty message

Revision ID: b10d2926bf0a
Revises: f4fa24207a1f
Create Date: 2019-10-20 23:00:19.958000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10d2926bf0a'
down_revision = 'f4fa24207a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
